package com.ryverbank.cms;

public class Content {
    // Content item info:
    //     {
    //         "id": (auto-generated by your api, int value),
    //         "title":"The title of the advisory or news",
    //         "summary":"The short summary of the content item",
    //         "content": "The text of the content item",
    //         "link":"https://link.to.externalcontent",
    //         "approved": true (or false)
    //     }

    @Id @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="content_id")
    private int id;

    private String title;
    private String summary;
    private String content;
    private String link;
    private boolean approved;

    // GETTERS
    public int getCID() { return this.id; }
    public String getTitle() { return this.title; }
    public String getSummary() { return this.summary; }
    public String getContent() { return this.content; }
    public String getLink() { return this.link; }
    public boolean getStatus() { return this.approved; }

    // SETTERS
    public void setTitle(String title) { this.title = title; }
    public void setSummary(String summary) { this.summary = summary; }
    public void setContent(String content) { this.content = content; }
    public void setLink(String link) { this.link = link; }
    public void setApproval(boolean approval) { this.approved = approval; }
}